# Generated by Django 3.0.8 on 2020-08-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200802_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='area',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='box',
            name='created_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='box',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='box',
            name='last_updated_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='box',
            name='length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='box',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='box',
            name='volume',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='box',
            name='width',
            field=models.IntegerField(),
        ),
    ]
