# Generated by Django 3.0.8 on 2020-08-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200802_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_area', models.IntegerField()),
                ('average_volume', models.IntegerField()),
                ('box_added_in_week', models.IntegerField()),
                ('box_added_by_user_in_week', models.IntegerField()),
            ],
        ),
    ]
